# Pandas Problems

1. Basic Exploration
Load the dataset into a Pandas DataFrame. Display:


*   The first 10 rows
*   The total number of rows and columns
*   Summary statistics for numerical columns

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/auto-mpg.csv')

In [4]:
# to show the first 10 rows
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [5]:
#To show total number of rows and columns
df.shape

(398, 9)

In [6]:
# to show Summary statistics for numerical columns
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

2. Filtering and Indexing:
Find all cars manufactured in 1975 with a weight less than 3000. Return the
DataFrame with selected columns: car_name, weight, and mpg.

In [7]:
#to find all cars manufactured in 1975 with a weight less than 3000 with car_name, weight, and mpg
df[(df['weight']<3000) & (df['model year']==75)][['car name', 'weight' , 'mpg']]

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

3. Handling Missing Data:
Identify if there are any missing values in the dataset. Replace missing values in the
horsepower column with the column's median.

In [8]:
#To check values in Horsepower and find '?'
print(df['horsepower'].unique())
#To convert the'?' to numeric form
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
median_hp = df['horsepower'].median()
df['horsepower'] = df['horsepower'].fillna(median_hp)
print(df.isna().sum())

['130' '165' '150' '140' '198' '220' '215' '225' '190' '170' '160' '95'
 '97' '85' '88' '46' '87' '90' '113' '200' '210' '193' '?' '100' '105'
 '175' '153' '180' '110' '72' '86' '70' '76' '65' '69' '60' '80' '54'
 '208' '155' '112' '92' '145' '137' '158' '167' '94' '107' '230' '49' '75'
 '91' '122' '67' '83' '78' '52' '61' '93' '148' '129' '96' '71' '98' '115'
 '53' '81' '79' '120' '152' '102' '108' '68' '58' '149' '89' '63' '48'
 '66' '139' '103' '125' '133' '138' '135' '142' '77' '62' '132' '84' '64'
 '74' '116' '82']
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [9]:
#To verify that all '?' are replaced now
print((df['horsepower'] == '?').sum())

0

4. Data Transformation :
Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [10]:
#To create new column
df['power to weight ratio'] = df['horsepower']/df['weight']
#To display first few rows
df.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power to weight ratio
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,0.040591

5. Group By :
Group the cars by origin and calculate the mean mpg for each group.

In [11]:
#Group by origin and calculate mean mpg
origin = df.groupby('origin')
origin['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

6. Sorting :  
Sort the DataFrame by mpg in descending order and display the top 10 cars with
the highest mpg.

In [30]:
# Sort by mpg in descending order
sorted_df = df.sort_values(by='mpg', ascending=False)
#To display top 10 cars
top_10 = sorted_df.head(10)
print(top_10[['car name', 'mpg']])

                            car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4

7. Apply this function to each row and store the result in the new column. Apply Function :
Create a new column performance_score using a custom function:
def performance_score(row):
return row['mpg'] * row['acceleration'] / row['weight']

In [13]:
#Define the function
def performance_score(row):
  return row['mpg'] * row['acceleration'] / row['weight']
#To apply a function to a row
df['performance_score'] = df.apply(performance_score, axis=1)
print(df.head(5))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model year  origin                   car name  power to weight ratio  \
0          70       1  chevrolet chevelle malibu               0.037100
1          70       1          buick skylark 320               0.044679
2          70       1         plymouth satellite               0.043655
3          70       1              amc rebel sst               0.043694
4          70       1                ford torino               0.040591

   performance_score
0           0.061644
1           0.046710
2           0.057625
3           0.055928
4           0.051754

8. Visualization Preparation -
Generate a summary DataFrame with:
○ Average mpg, weight, and horsepower for each model_year.

In [14]:
#Group by model year and calculate mean
summary = df.groupby('model year')
summary[['mpg', 'weight', 'horsepower']].mean()

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

9. Exporting Data -
Save a subset of the data containing only mpg, cylinders, horsepower, and weight
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [15]:
#to filter data
high_mpg = df[(df['mpg']>30)]
subsets = high_mpg[['mpg', 'cylinders', 'horsepower', 'weight']]
print(subsets)
#Save to csv
subsets.to_csv('high_mpg_cars.csv', index=False)

      mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649
..    ...        ...         ...     ...
390  32.0          4        96.0    2665
391  36.0          4        84.0    2370
394  44.0          4        52.0    2130
395  32.0          4        84.0    2295
397  31.0          4        82.0    2720

[85 rows x 4 columns]

10. Finding Anomalies -
Identify potential outliers in the mpg column using the Interquartile Range (IQR)
method. Specifically:
● Calculate the IQR for mpg. ● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 +
1.5 * IQR.
● Create a DataFrame of cars classified as outliers, displaying car_name, mpg,
and model_year.

In [16]:
#To calculate Q1, Q3 and IQR
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3-Q1

#To define outlier condition
outliers = df[(df['mpg'] < (Q1 - 1.5 * IQR)) |
              (df['mpg'] > (Q3 + 1.5 * IQR))]
cars = outliers[['car name', 'mpg', 'model year']]
print(cars)

      car name   mpg  model year
322  mazda glc  46.6          80

# NumPy Problems

1. Basic Array Operations :
Convert the mpg column into a NumPy array and calculate:
○ The mean, median, and standard deviation of mpg.
○ The number of cars with mpg greater than 25.

In [17]:
import numpy as np
mpg_array = df['mpg'].values

#To find mean, median and standard deviation
mean_mpg = np.mean(mpg_array)
median_mpg = np.median(mpg_array)
std_mpg = np.std(mpg_array)

print("Mean:", mean_mpg)
print("Median:", median_mpg)
print("Standard Deviation:", std_mpg)

# Count cars with mpg > 25
count = np.sum(mpg_array > 25)

print("Number of cars with mpg > 25:", count)

Mean: 23.514572864321607
Median: 23.0
Standard Deviation: 7.806159061274433
Number of cars with mpg > 25: 158

2. Filtering :
Using NumPy, filter all cars with more than 6 cylinders.
Return the corresponding car_name as a list.

In [18]:
#To filter all cars with more than 6 cylinders
cylinders = df['cylinders'].values
car_names = df['car name'].values

# Filter condition
filtered_names = car_names[cylinders > 6]

# Convert to list
result = filtered_names.tolist()

print(result)

['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino', 'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii', 'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se', "plymouth 'cuda 340", 'chevrolet monte carlo', 'buick estate wagon (sw)', 'ford f250', 'chevy c20', 'dodge d200', 'hi 1200d', 'chevrolet impala', 'pontiac catalina brougham', 'ford galaxie 500', 'plymouth fury iii', 'dodge monaco (sw)', 'ford country squire (sw)', 'pontiac safari (sw)', 'chevrolet impala', 'pontiac catalina', 'plymouth fury iii', 'ford galaxie 500', 'amc ambassador sst', 'mercury marquis', 'buick lesabre custom', 'oldsmobile delta 88 royale', 'chrysler newport royal', 'amc matador (sw)', 'chevrolet chevelle concours (sw)', 'ford gran torino (sw)', 'plymouth satellite custom (sw)', 'buick century 350', 'amc matador', 'chevrolet malibu', 'ford gran torino', 'dodge coronet custom', 'mercury marquis brougham', 'chevrolet caprice classic', 'ford ltd', 'plymouth fury gran sedan', 'chrysler new yorker brougham', 'buick electra 225 custom', 'amc ambassador brougham', 'chevrolet impala', 'ford country', 'plymouth custom suburb', 'oldsmobile vista cruiser', 'chevrolet monte carlo s', 'pontiac grand prix', 'dodge dart custom', 'oldsmobile omega', 'ford gran torino', 'buick century luxus (sw)', 'dodge coronet custom (sw)', 'ford gran torino (sw)', 'amc matador (sw)', 'pontiac catalina', 'chevrolet bel air', 'plymouth grand fury', 'ford ltd', 'chevrolet monza 2+2', 'ford mustang ii', 'chevrolet chevelle malibu classic', 'dodge coronet brougham', 'amc matador', 'ford gran torino', 'plymouth volare premier v8', 'cadillac seville', 'chevy c10', 'ford f108', 'dodge d100', 'chevrolet caprice classic', 'oldsmobile cutlass supreme', 'dodge monaco brougham', 'mercury cougar brougham', 'pontiac grand prix lj', 'chevrolet monte carlo landau', 'chrysler cordoba', 'ford thunderbird', 'oldsmobile cutlass salon brougham', 'dodge diplomat', 'mercury monarch ghia', 'chevrolet monte carlo landau', 'ford futura', 'dodge magnum xe', 'chevrolet caprice classic', 'ford ltd landau', 'mercury grand marquis', 'dodge st. regis', 'buick estate wagon (sw)', 'ford country squire (sw)', 'chevrolet malibu classic (sw)', 'chrysler lebaron town @ country (sw)', 'cadillac eldorado', 'oldsmobile cutlass salon brougham', 'oldsmobile cutlass ls']

3. Statistical Analysis :
Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [19]:
#Converting weight column to NumPy array
weight_array = df['weight'].values
#To calculate percentiles
q1 = np.percentile(weight_array, 25)
q2 = np.percentile(weight_array, 50)
q3 = np.percentile(weight_array, 75)

print("25th percentile (Q1):", q1)
print("50th percentile (Median):", q2)
print("75th percentile (Q3):", q3)

25th percentile (Q1): 2223.75
50th percentile (Median): 2803.5
75th percentile (Q3): 3608.0

4. Array Manipulation :
Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [20]:
#Convert acceleration to NumPy array
acc_array = df['acceleration'].values
# Find min and max
min_val = np.min(acc_array)
max_val = np.max(acc_array)

# Normalize
normalized = (acc_array - min_val) / (max_val - min_val)
#display first 10 values
print(normalized[:10])

[0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619 ]

5. Broadcasting :
Increase all horsepower values by 10% and store the updated values in a new
NumPy array. Handle missing data (if any) by replacing it with the mean of the
column before applying the increase.

In [21]:
# Convert 'horsepower' to numeric
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

# Replace missing values with mean
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

# Convert to NumPy array
hp_array = df['horsepower'].values

# Increase horsepower by 10%
new_hp = hp_array * 1.10

print(new_hp[:10])

[143.  181.5 165.  165.  154.  217.8 242.  236.5 247.5 209. ]

6. Boolean Indexing :
Find the average displacement of cars with an origin of 2 (Europe) using NumPy
indexing.

In [22]:
# Convert required columns to NumPy arrays
displacement = df['displacement'].values
origin = df['origin'].values
# Apply condition (origin == 2)
filtered_dp = displacement[origin == 2]

# Calculate average
avg_displacement = np.mean(filtered_dp)

print("Average displacement (origin = 2):", avg_displacement)

Average displacement (origin = 2): 109.14285714285714

7. Matrix Operations :
Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [23]:
# Extract required columns as NumPy arrays
mpg = df['mpg'].values
horsepower = df['horsepower'].values
weight = df['weight'].values
# Create 2D array (matrix)
matrix = np.column_stack((mpg, horsepower, weight))

# Define vector
vector = np.array([1, 0.5, -0.2])

# Compute dot product
result = np.dot(matrix, vector)

print(result[:10])

[-617.8 -641.1 -594.2 -595.6 -602.8 -754.2 -746.8 -740.9 -758.5 -660. ]

8. Sorting :
Use NumPy to sort the cars by model_year in descending order and display the first
f
ive car names.

In [26]:
# Convert required columns to NumPy arrays
model_year = df['model year'].values
car_names = df['car name'].values

# Get sorted indices (descending order)
sorted = np.argsort(model_year)[::-1]

# Get top 5 car names
top_5_cars = car_names[sorted][:5]

print(top_5_cars)

['dodge aries se' 'pontiac phoenix' 'pontiac j2000 se hatchback'
 'chevrolet cavalier 2-door' 'chevrolet cavalier wagon']

9. Correlation :
Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [27]:
# Convert columns to NumPy arrays
mpg = df['mpg'].values
weight = df['weight'].values

# Compute correlation matrix
corr_matrix = np.corrcoef(mpg, weight)

# Extract correlation value
correlation = corr_matrix[0, 1]

print("Pearson correlation:", correlation)

Pearson correlation: -0.8317409332443352

10. Conditional Aggregates :
Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [28]:
#Convert columns to NumPy arrays
mpg = df['mpg'].values
cylinders = df['cylinders'].values

# Get unique cylinder values
unique_cyl = np.unique(cylinders)

# Calculate mean mpg for each group
for cyl in unique_cyl:
    mean_mpg = np.mean(mpg[cylinders == cyl])
    print(f"Cylinders: {cyl}, Mean MPG: {mean_mpg}")

Cylinders: 3, Mean MPG: 20.55
Cylinders: 4, Mean MPG: 29.28676470588235
Cylinders: 5, Mean MPG: 27.366666666666664
Cylinders: 6, Mean MPG: 19.985714285714284
Cylinders: 8, Mean MPG: 14.963106796116506